esphome:
  name: ultimate-solar-controller

esp32:
  board: esp32dev
  framework:
    type: arduino
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: i2c0
time:
  - platform: homeassistant  
    id: homeassistant_time
    on_time: # Every minute
      - seconds: 0
        minutes: /1
        then: # Output sun azimuth and elevation
          - logger.log: 
              format: "Sun position: Azimuth %.1f, Elevation %.1f"
              args: ['id(sunpos).azimuth()', 'id(sunpos).elevation()']
sun:
    id: sunpos
    latitude: 53.198071
    longitude: -0.467950
# Enable logging
logger:

# Enable Home Assistant API
api:
switch:
  - platform: gpio
    name: "Relay 1"
    pin: GPIO32
    id: relay1
    interlock: [relay2,relay3,relay4,relay5,relay6]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 2"
    pin: GPIO14
    id: relay2
    interlock: [relay1,relay3,relay4,relay5,relay6]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 3"
    pin: GPIO27
    id: relay3
    interlock: [relay2,relay1,relay4,relay5,relay6]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 4"
    pin: GPIO26
    id: relay4
    interlock: [relay2,relay3,relay1,relay5,relay6]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 5"
    pin: GPIO25
    id: relay5
    interlock: [relay2,relay3,relay4,relay1,relay6]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 6"
    pin: GPIO33
    id: relay6
    interlock: [relay2,relay3,relay4,relay5,relay1]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_OFF
sensor:
  - platform: sun
    name: Sun Elevation
    type: elevation
  - platform: sun
    name: Sun Azimuth
    type: azimuth
  - platform: template
    id: target_panel_elevation
    name: "Targer Panel elevation"
    lambda: |-
      return 90-(id(sunpos).elevation());
    update_interval: 30000ms

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ultimate-Solar-Controller"
    password: !secret wifi_password

captive_portal:
